package com.logan.mybatis6.bean;

import java.io.Serializable;

public class CstCustomer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_source
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String custSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_industry
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String custIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_level
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String custLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_address
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String custAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_phone
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String custPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_customer
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_id
     *
     * @return the value of cst_customer.cust_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_id
     *
     * @param custId the value for cst_customer.cust_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_name
     *
     * @return the value of cst_customer.cust_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_name
     *
     * @param custName the value for cst_customer.cust_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_source
     *
     * @return the value of cst_customer.cust_source
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getCustSource() {
        return custSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_source
     *
     * @param custSource the value for cst_customer.cust_source
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustSource(String custSource) {
        this.custSource = custSource == null ? null : custSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_industry
     *
     * @return the value of cst_customer.cust_industry
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getCustIndustry() {
        return custIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_industry
     *
     * @param custIndustry the value for cst_customer.cust_industry
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustIndustry(String custIndustry) {
        this.custIndustry = custIndustry == null ? null : custIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_level
     *
     * @return the value of cst_customer.cust_level
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_level
     *
     * @param custLevel the value for cst_customer.cust_level
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustLevel(String custLevel) {
        this.custLevel = custLevel == null ? null : custLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_address
     *
     * @return the value of cst_customer.cust_address
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_address
     *
     * @param custAddress the value for cst_customer.cust_address
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_phone
     *
     * @return the value of cst_customer.cust_phone
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_phone
     *
     * @param custPhone the value for cst_customer.cust_phone
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_customer
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custId=").append(custId);
        sb.append(", custName=").append(custName);
        sb.append(", custSource=").append(custSource);
        sb.append(", custIndustry=").append(custIndustry);
        sb.append(", custLevel=").append(custLevel);
        sb.append(", custAddress=").append(custAddress);
        sb.append(", custPhone=").append(custPhone);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}