package com.logan.mybatis6.bean;

import java.io.Serializable;

public class CstLinkman implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private Long lkmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_gender
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_phone
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_mobile
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_email
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_position
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_memo
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String lkmMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_cust_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private Long lkmCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_linkman
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_id
     *
     * @return the value of cst_linkman.lkm_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public Long getLkmId() {
        return lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_id
     *
     * @param lkmId the value for cst_linkman.lkm_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmId(Long lkmId) {
        this.lkmId = lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_name
     *
     * @return the value of cst_linkman.lkm_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmName() {
        return lkmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_name
     *
     * @param lkmName the value for cst_linkman.lkm_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmName(String lkmName) {
        this.lkmName = lkmName == null ? null : lkmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_gender
     *
     * @return the value of cst_linkman.lkm_gender
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmGender() {
        return lkmGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_gender
     *
     * @param lkmGender the value for cst_linkman.lkm_gender
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmGender(String lkmGender) {
        this.lkmGender = lkmGender == null ? null : lkmGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_phone
     *
     * @return the value of cst_linkman.lkm_phone
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmPhone() {
        return lkmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_phone
     *
     * @param lkmPhone the value for cst_linkman.lkm_phone
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmPhone(String lkmPhone) {
        this.lkmPhone = lkmPhone == null ? null : lkmPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_mobile
     *
     * @return the value of cst_linkman.lkm_mobile
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmMobile() {
        return lkmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_mobile
     *
     * @param lkmMobile the value for cst_linkman.lkm_mobile
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmMobile(String lkmMobile) {
        this.lkmMobile = lkmMobile == null ? null : lkmMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_email
     *
     * @return the value of cst_linkman.lkm_email
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmEmail() {
        return lkmEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_email
     *
     * @param lkmEmail the value for cst_linkman.lkm_email
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmEmail(String lkmEmail) {
        this.lkmEmail = lkmEmail == null ? null : lkmEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_position
     *
     * @return the value of cst_linkman.lkm_position
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmPosition() {
        return lkmPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_position
     *
     * @param lkmPosition the value for cst_linkman.lkm_position
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmPosition(String lkmPosition) {
        this.lkmPosition = lkmPosition == null ? null : lkmPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_memo
     *
     * @return the value of cst_linkman.lkm_memo
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getLkmMemo() {
        return lkmMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_memo
     *
     * @param lkmMemo the value for cst_linkman.lkm_memo
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmMemo(String lkmMemo) {
        this.lkmMemo = lkmMemo == null ? null : lkmMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_cust_id
     *
     * @return the value of cst_linkman.lkm_cust_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public Long getLkmCustId() {
        return lkmCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_cust_id
     *
     * @param lkmCustId the value for cst_linkman.lkm_cust_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setLkmCustId(Long lkmCustId) {
        this.lkmCustId = lkmCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_linkman
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lkmId=").append(lkmId);
        sb.append(", lkmName=").append(lkmName);
        sb.append(", lkmGender=").append(lkmGender);
        sb.append(", lkmPhone=").append(lkmPhone);
        sb.append(", lkmMobile=").append(lkmMobile);
        sb.append(", lkmEmail=").append(lkmEmail);
        sb.append(", lkmPosition=").append(lkmPosition);
        sb.append(", lkmMemo=").append(lkmMemo);
        sb.append(", lkmCustId=").append(lkmCustId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}