package com.logan.mybatis6.bean;

import java.io.Serializable;

public class ScoreKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.s_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.c_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.s_id
     *
     * @return the value of score.s_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.s_id
     *
     * @param sId the value for score.s_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.c_id
     *
     * @return the value of score.c_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.c_id
     *
     * @param cId the value for score.c_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sId=").append(sId);
        sb.append(", cId=").append(cId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}