package com.logan.mybatis6.bean;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_birth
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String sBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_sex
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private String sSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param sId the value for student.s_id
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_birth
     *
     * @return the value of student.s_birth
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getsBirth() {
        return sBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_birth
     *
     * @param sBirth the value for student.s_birth
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setsBirth(String sBirth) {
        this.sBirth = sBirth == null ? null : sBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_sex
     *
     * @return the value of student.s_sex
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_sex
     *
     * @param sSex the value for student.s_sex
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Thu Mar 26 10:35:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sId=").append(sId);
        sb.append(", sName=").append(sName);
        sb.append(", sBirth=").append(sBirth);
        sb.append(", sSex=").append(sSex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}